name: Create VPS
on:
  workflow_dispatch:

jobs:
  vps:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - name: Install SSHX
        run: curl -sSf https://sshx.io/get | sh
      - name: Start SSHX
        run: sshx run
      - name: Keep Alive
        run: sleep 21600
